#docker-compose up -d
version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always #unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    ports:
      - 8002:8081
    networks:
      - mongo-database

  note_app_node:
    image: note_app_node:latest
    container_name: note_app_node
    working_dir: /app
    environment:
      EXP_CONFIG_DATABASE_NAME: node_app
      EXP_CONFIG_DATABASE_HOST: mongodb
      EXP_CONFIG_DATABASE_PORT: 27017
      EXP_CONFIG_SECRET_KEY: bhagyesh
      EXP_CONFIG_EXPIRY_TIME: 3600
      EXP_CONFIG_PROJECT_PORT: 9052
    ports:
      - "9052:9052"
    expose:
      - "9052"
    networks:
      - mongo-database

networks:
  mongo-database:
    driver: bridge